---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Add Nginx signing key
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add Nginx repository
  ansible.builtin.apt_repository:
    repo: "deb https://nginx.org/packages/mainline/ubuntu {{ ansible_facts['distribution_release'] }} nginx"
    state: present
    filename: nginx

- name: Install the latest Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
