---
- block:
    - name: Nginx | Disable default config
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify: reload nginx

    - name: Nginx | create directories
      ansible.builtin.file:
        path: /etc/nginx/sites-available
        state: directory
        mode: "0755"

    - name: Nginx | Configure http upgrade for each domain
      ansible.builtin.template:
        src: nginx_http.conf.j2
        dest: "/etc/nginx/sites-available/nginx_http"
      notify: reload nginx

    - name: Nginx | Enable upgrade config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/nginx_http"
        dest: "/etc/nginx/conf.d/nginx_http.conf"
        state: link
      notify: reload nginx

    - name: Nginx | Configure for each domain
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-available/{{ item.domain }}"
      loop: "{{ nginx_configs }}"
      notify: reload nginx

    - name: Nginx | Enable site configs
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item.domain }}"
        dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
        state: link
      loop: "{{ nginx_configs }}"
      notify: reload nginx

  tags:
    - nginx
    - nginx-configure
