---
- name: Disable default Nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Configure Nginx http upgrade for each domain
  template:
    src: nginx_http.conf.j2
    dest: "/etc/nginx/sites-available/nginx_http"
  notify: reload nginx

- name: Enable upgrade config
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/nginx_http"
    dest: "/etc/nginx/sites-enabled/nginx_http"
    state: link
  notify: reload nginx

- name: Configure Nginx for each domain
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.domain }}"
  loop: "{{ nginx_configs }}"
  notify: reload nginx

- name: Enable site configs
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item.domain }}"
    dest: "/etc/nginx/sites-enabled/{{ item.domain }}"
    state: link
  loop: "{{ nginx_configs }}"
  notify: reload nginx
