---
- name: Docker | Add signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    

- name: Docker | Add repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker.list
    update_cache: true

- name: Docker | Install packages.
  package:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "docker-ce-rootless-extras"
      - "containerd.io"
      - docker-buildx-plugin
    state: present
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: Docker | Install docker-compose plugin.
  package:
    name: docker-compose-plugin
    state: present
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: Docker | Ensure /etc/docker/ directory exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0755
